#!/bin/bash
yum install -y docker
service docker start
usermod -aG docker ec2-user
mkdir AWS-jupyter
cd AWS-jupyter
curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod a+x /usr/local/bin/docker-compose
aws s3 cp s3://docker-compose/docker-compose.yml docker-compose.yml
docker-compose up -d
